# Build chapter 15 门户管理
lines = []
lines.append('---')
lines.append('')
lines.append('## 十五、门户管理')
lines.append('')
lines.append('> **功能路径**：`/portal` 模块')
lines.append('> **权限要求**：租户管理员（tenant_admin）')
lines.append('> **套餐要求**：基础版及以上')
lines.append('')
lines.append('### 15.1 门户页面')
lines.append('')
lines.append('#### 15.1.1 功能描述')
lines.append('可视化门户页面配置，支持拖拽布局、添加组件、设置主题样式。')
lines.append('')
lines.append('#### 15.1.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| page_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| page_name | VARCHAR(50) | 页面名称 |')
lines.append('| page_code | VARCHAR(30) | 页面编码 |')
lines.append('| page_type | ENUM | dashboard / landing / custom |')
lines.append('| layout_config | JSONB | 布局配置 |')
lines.append('| components | JSONB | 组件列表 |')
lines.append('| theme | JSONB | 主题样式 |')
lines.append('| is_default | BOOLEAN | 是否默认首页 |')
lines.append('| status | ENUM | draft / published / archived |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('| updated_at | TIMESTAMPTZ | 更新时间 |')
lines.append('')
lines.append('#### 15.1.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/pages` | 页面列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/pages` | 创建页面 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/pages/{id}` | 页面详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/portal/pages/{id}` | 更新页面 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/portal/pages/{id}` | 删除页面 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/pages/{id}/publish` | 发布页面 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/pages/{id}/preview` | 预览页面 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/portal/pages/{id}/set-default` | 设为默认页面 |')
lines.append('')
lines.append('#### 15.1.4 按钮定义')
lines.append('**页面路径**: `/portal/pages`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建页面」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开设计器 | tenant_admin |')
lines.append('| 表格行 | 「预览」 | 新窗口打开 | all |')
lines.append('| 表格行 | 「发布」 | 确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「设默认」 | 确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 15.2 门户注册')
lines.append('')
lines.append('#### 15.2.1 功能描述')
lines.append('将低代码页面或外部 URL 注册为门户菜单项，供用户访问。')
lines.append('')
lines.append('#### 15.2.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| portal_item_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| page_id | UUID | 关联页面 |')
lines.append('| item_name | VARCHAR(50) | 菜单名称 |')
lines.append('| item_icon | VARCHAR(50) | 图标 |')
lines.append('| sort_order | INT | 排序 |')
lines.append('| visible | BOOLEAN | 是否显示 |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 15.2.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/items` | 门户菜单列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/items` | 注册门户项 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/portal/items/{id}` | 更新门户项 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/portal/items/{id}` | 删除门户项 |')
lines.append('')
lines.append('#### 15.2.4 按钮定义')
lines.append('**页面路径**: `/portal/items`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「注册」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 15.3 门户新闻配置')
lines.append('')
lines.append('#### 15.3.1 功能描述')
lines.append('新闻模块配置，支持配置新闻列表样式、详情页模板和评论规则。')
lines.append('')
lines.append('#### 15.3.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| news_config_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| list_template | VARCHAR(50) | 列表模板 |')
lines.append('| detail_template | VARCHAR(50) | 详情模板 |')
lines.append('| allow_comment | BOOLEAN | 是否允许评论 |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 15.3.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/news/config` | 获取新闻配置 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/portal/news/config` | 更新新闻配置 |')
lines.append('')
lines.append('#### 15.3.4 按钮定义')
lines.append('**页面路径**: `/portal/news/config`')
lines.append('**布局**: 表单页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（右） | 「保存」 | 保存表单 | tenant_admin |')
lines.append('')
lines.append('### 15.4 新闻栏目')
lines.append('')
lines.append('#### 15.4.1 功能描述')
lines.append('新闻分类栏目管理，支持多级栏目结构。')
lines.append('')
lines.append('#### 15.4.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| column_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| parent_id | UUID | 上级栏目 |')
lines.append('| column_name | VARCHAR(50) | 栏目名称 |')
lines.append('| column_code | VARCHAR(30) | 栏目编码 |')
lines.append('| sort_order | INT | 排序 |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 15.4.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/news/columns` | 栏目列表（树形） |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/news/columns` | 新建栏目 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/portal/news/columns/{id}` | 更新栏目 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/portal/news/columns/{id}` | 删除栏目 |')
lines.append('')
lines.append('#### 15.4.4 按钮定义')
lines.append('**页面路径**: `/portal/news/columns`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建栏目」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 15.5 新闻发布')
lines.append('')
lines.append('#### 15.5.1 功能描述')
lines.append('新闻内容发布管理，支持富文本编辑、附件上传和定时发布。')
lines.append('')
lines.append('#### 15.5.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| article_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| column_id | UUID | 所属栏目 |')
lines.append('| title | VARCHAR(200) | 文章标题 |')
lines.append('| author | VARCHAR(50) | 作者 |')
lines.append('| content | TEXT | 文章内容（富文本） |')
lines.append('| cover_image | VARCHAR(500) | 封面图片 |')
lines.append('| attachments | JSONB | 附件列表 |')
lines.append('| publish_time | TIMESTAMPTZ | 发布时间 |')
lines.append('| status | ENUM | draft / published / archived |')
lines.append('| view_count | INT | 阅读量 |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('| updated_at | TIMESTAMPTZ | 更新时间 |')
lines.append('')
lines.append('#### 15.5.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/news/articles` | 文章列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/news/articles` | 创建文章 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/news/articles/{id}` | 文章详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/portal/news/articles/{id}` | 更新文章 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/portal/news/articles/{id}` | 删除文章 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/news/articles/{id}/publish` | 发布文章 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/news/articles/{id}/offline` | 下架文章 |')
lines.append('')
lines.append('#### 15.5.4 按钮定义')
lines.append('**页面路径**: `/portal/news/articles`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（左） | 「栏目筛选」 | 下拉筛选 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建文章」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「发布」 | 确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「下架」 | 确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 15.6 预警消息设置')
lines.append('')
lines.append('#### 15.6.1 功能描述')
lines.append('预警规则配置，支持按设备、会员、订单等业务对象设置预警条件和通知方式。')
lines.append('')
lines.append('#### 15.6.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| alert_config_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| alert_name | VARCHAR(50) | 预警名称 |')
lines.append('| alert_code | VARCHAR(30) | 预警编码 |')
lines.append('| target_type | ENUM | device / member / order / custom |')
lines.append('| condition_expr | TEXT | 条件表达式 |')
lines.append('| threshold | JSONB | 阈值配置 |')
lines.append('| notify_channels | VARCHAR[] | 通知渠道（sms/email/站内） |')
lines.append('| notify_users | UUID[] | 通知用户列表 |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 15.6.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/alerts/configs` | 预警配置列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/alerts/configs` | 新建预警配置 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/alerts/configs/{id}` | 配置详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/portal/alerts/configs/{id}` | 更新配置 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/portal/alerts/configs/{id}` | 删除配置 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/alerts/configs/{id}/test` | 测试预警 |')
lines.append('')
lines.append('#### 15.6.4 按钮定义')
lines.append('**页面路径**: `/portal/alerts/configs`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建配置」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「测试」 | 确认弹窗后测试 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 15.7 预警信息')
lines.append('')
lines.append('#### 15.7.1 功能描述')
lines.append('预警信息列表，展示触发的预警事件，支持确认、处理和批量处理。')
lines.append('')
lines.append('#### 15.7.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| alert_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| alert_config_id | UUID | 预警配置ID |')
lines.append('| alert_name | VARCHAR(50) | 预警名称 |')
lines.append('| target_type | VARCHAR(50) | 业务对象类型 |')
lines.append('| target_id | UUID | 业务对象ID |')
lines.append('| target_name | VARCHAR(100) | 业务对象名称 |')
lines.append('| alert_level | ENUM | info / warning / critical |')
lines.append('| alert_message | TEXT | 预警消息 |')
lines.append('| alert_time | TIMESTAMPTZ | 预警时间 |')
lines.append('| status | ENUM | pending / confirmed / resolved |')
lines.append('| confirmed_by | UUID | 确认人 |')
lines.append('| confirmed_at | TIMESTAMPTZ | 确认时间 |')
lines.append('| resolved_by | UUID | 处理人 |')
lines.append('| resolved_at | TIMESTAMPTZ | 处理时间 |')
lines.append('| resolution | TEXT | 处理结果 |')
lines.append('')
lines.append('#### 15.7.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/alerts` | 预警列表 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/alerts/{id}` | 预警详情 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/alerts/{id}/confirm` | 确认预警 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/alerts/{id}/resolve` | 处理预警 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/alerts/batch-confirm` | 批量确认 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/alerts/history` | 预警流水 |')
lines.append('')
lines.append('#### 15.7.4 按钮定义')
lines.append('**页面路径**: `/portal/alerts`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（左） | 「级别筛选」 | 下拉筛选 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「批量确认」 | 勾选后批量确认 | tenant_admin |')
lines.append('| 表格行 | 「详情」 | 打开全屏模态 | all |')
lines.append('| 表格行 | 「确认」 | 确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「处理」 | 打开抽屉 | tenant_admin |')
lines.append('')
lines.append('### 15.8 预警消息流水')
lines.append('')
lines.append('#### 15.8.1 功能描述')
lines.append('预警消息发送流水记录，记录每条预警的通知发送状态。')
lines.append('')
lines.append('#### 15.8.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| alert_log_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| alert_id | UUID | 关联预警ID |')
lines.append('| notify_channel | ENUM | sms / email / in_app |')
lines.append('| recipient | VARCHAR(100) | 接收人 |')
lines.append('| send_status | ENUM | pending / sent / failed |')
lines.append('| send_time | TIMESTAMPTZ | 发送时间 |')
lines.append('| error_message | VARCHAR(200) | 错误信息 |')
lines.append('')
lines.append('#### 15.8.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/portal/alerts/logs` | 预警流水列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/portal/alerts/{id}/resend` | 重新发送 |')
lines.append('')
lines.append('#### 15.8.4 按钮定义')
lines.append('**页面路径**: `/portal/alerts/logs`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 表格行 | 「重发」 | 确认弹窗 | tenant_admin |')
content = '\n'.join(lines)
with open(r'C:\Users\YKing\.openclaw\workspace\new_ch15.txt', 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Ch15: {len(content)} chars')
