# Build chapter 14 content
lines = []
lines.append('---')
lines.append('')
lines.append('## 十四、低代码CRUD')
lines.append('')
lines.append('> **功能路径**：`/lowcode` 模块')
lines.append('> **权限要求**：租户管理员（tenant_admin）')
lines.append('> **套餐要求**：专业版及以上')
lines.append('')
lines.append('### 14.1 标准CRUD')
lines.append('')
lines.append('#### 14.1.1 功能描述')
lines.append('通用 CRUD 生成器，通过配置数据模型自动生成标准列表页、详情页、表单页和对应 API。')
lines.append('')
lines.append('#### 14.1.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| model_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| model_name | VARCHAR(50) | 模型名称 |')
lines.append('| model_code | VARCHAR(30) | 模型编码（英文，唯一） |')
lines.append('| table_name | VARCHAR(50) | 对应数据库表名 |')
lines.append('| fields | JSONB | 字段定义数组 |')
lines.append('| list_config | JSONB | 列表页配置 |')
lines.append('| form_config | JSONB | 表单页配置 |')
lines.append('| api_config | JSONB | API 配置 |')
lines.append('| status | ENUM | draft / generated / published |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 14.1.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/models` | 模型列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/lowcode/models` | 创建数据模型 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/models/{id}` | 模型详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/lowcode/models/{id}` | 更新模型 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/lowcode/models/{id}` | 删除模型 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/lowcode/models/{id}/generate` | 生成 CRUD 代码 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/lowcode/models/{id}/preview` | 预览生成结果 |')
lines.append('')
lines.append('#### 14.1.4 按钮定义')
lines.append('**页面路径**: `/lowcode/models`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建模型」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「生成代码」 | 确认弹窗后生成 | tenant_admin |')
lines.append('| 表格行 | 「预览」 | 打开抽屉 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 14.2 注册报表功能')
lines.append('')
lines.append('#### 14.2.1 功能描述')
lines.append('将低代码生成的模型注册为报表功能，供数据分析模块调用。')
lines.append('')
lines.append('#### 14.2.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| report_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| model_id | UUID | 关联数据模型 |')
lines.append('| report_name | VARCHAR(50) | 报表名称 |')
lines.append('| report_code | VARCHAR(30) | 报表编码 |')
lines.append('| chart_type | ENUM | table / line / bar / pie |')
lines.append('| dimensions | VARCHAR[] | 维度字段 |')
lines.append('| metrics | VARCHAR[] | 指标字段 |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 14.2.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/reports` | 报表列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/lowcode/reports` | 注册报表 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/reports/{id}` | 报表详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/lowcode/reports/{id}` | 更新报表配置 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/lowcode/reports/{id}` | 删除报表 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/reports/{id}/data` | 获取报表数据 |')
lines.append('')
lines.append('#### 14.2.4 按钮定义')
lines.append('**页面路径**: `/lowcode/reports`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「注册报表」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「数据」 | 路由跳转数据页 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 14.3 树表格CRUD')
lines.append('')
lines.append('#### 14.3.1 功能描述')
lines.append('支持树形层级数据的 CRUD，适用于组织架构、商品分类等层级数据管理。')
lines.append('')
lines.append('#### 14.3.2 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/tree/{model_code}` | 获取树形列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/lowcode/tree/{model_code}` | 新增树节点 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/lowcode/tree/{model_code}/{id}` | 更新树节点 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/lowcode/tree/{model_code}/{id}` | 删除树节点 |')
lines.append('')
lines.append('#### 14.3.3 按钮定义')
lines.append('**页面路径**: `/lowcode/tree/{model_code}`')
lines.append('**布局**: 树形列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新增」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「新增子节点」 | 打开全屏模态 | tenant_admin |')
lines.append('')
lines.append('### 14.4 标准CRUD追加子表')
lines.append('')
lines.append('#### 14.4.1 功能描述')
lines.append('主子表模式，在标准 CRUD 基础上追加明细子表，支持一对多数据关联。')
lines.append('')
lines.append('#### 14.4.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| relation_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| master_model_id | UUID | 主表模型 |')
lines.append('| detail_model_id | UUID | 子表模型 |')
lines.append('| relation_type | ENUM | one_to_many / many_to_many |')
lines.append('| foreign_key | VARCHAR(50) | 外键字段名 |')
lines.append('| cascade_delete | BOOLEAN | 级联删除 |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 14.4.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/relations` | 关联列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/lowcode/relations` | 创建关联 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/relations/{id}` | 关联详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/lowcode/relations/{id}` | 更新关联 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/lowcode/relations/{id}` | 删除关联 |')
lines.append('')
lines.append('#### 14.4.4 按钮定义')
lines.append('**页面路径**: `/lowcode/relations`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建关联」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 14.5 测试Post请求')
lines.append('')
lines.append('#### 14.5.1 功能描述')
lines.append('API 测试工具，支持发送 POST 请求并查看响应结果。')
lines.append('')
lines.append('#### 14.5.2 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/lowcode/test/post` | 发送 POST 测试请求 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/test/history` | 测试历史记录 |')
lines.append('')
lines.append('#### 14.5.3 按钮定义')
lines.append('**页面路径**: `/lowcode/api-tester`')
lines.append('**布局**: 表单页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（右） | 「发送」 | 发送请求并显示响应 | all |')
lines.append('| 操作栏（右） | 「清空」 | 清空表单 | all |')
lines.append('')
lines.append('### 14.6 会话管理')
lines.append('')
lines.append('#### 14.6.1 功能描述')
lines.append('查看当前用户的登录会话，支持强制下线。')
lines.append('')
lines.append('#### 14.6.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| session_id | UUID | 会话ID |')
lines.append('| user_id | UUID | 用户ID |')
lines.append('| device_info | VARCHAR(200) | 设备信息 |')
lines.append('| ip_address | VARCHAR(50) | IP 地址 |')
lines.append('| created_at | TIMESTAMPTZ | 登录时间 |')
lines.append('| expires_at | TIMESTAMPTZ | 过期时间 |')
lines.append('| is_current | BOOLEAN | 是否当前会话 |')
lines.append('')
lines.append('#### 14.6.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/sessions` | 会话列表 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/sessions/{id}` | 强制下线 |')
lines.append('')
lines.append('#### 14.6.4 按钮定义')
lines.append('**页面路径**: `/lowcode/sessions`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「刷新」 | 刷新列表 | all |')
lines.append('| 表格行 | 「强制下线」 | 确认弹窗 | all |')
lines.append('')
lines.append('### 14.7 单据类CRUD')
lines.append('')
lines.append('#### 14.7.1 功能描述')
lines.append('单据流程模式，在 CRUD 基础上关联审批流程，支持单据的提交、审批、归档全生命周期管理。')
lines.append('')
lines.append('#### 14.7.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| doc_type_id | UUID | 单据类型主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| doc_type_name | VARCHAR(50) | 单据类型名称 |')
lines.append('| doc_type_code | VARCHAR(30) | 单据类型编码 |')
lines.append('| model_id | UUID | 关联数据模型 |')
lines.append('| process_def_id | UUID | 关联审批流程 |')
lines.append('| doc_prefix | VARCHAR(10) | 单据号前缀 |')
lines.append('| doc_sequence | INT | 当前序号 |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 14.7.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/doc-types` | 单据类型列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/lowcode/doc-types` | 创建单据类型 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/doc-types/{id}` | 单据类型详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/lowcode/doc-types/{id}` | 更新单据类型 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/lowcode/doc-types/{id}` | 删除单据类型 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/lowcode/docs/{type_code}` | 提交单据 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/docs/{type_code}` | 单据列表 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/lowcode/docs/{type_code}/{id}` | 单据详情 |')
lines.append('')
lines.append('#### 14.7.4 按钮定义')
lines.append('**页面路径**: `/lowcode/doc-types`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建单据类型」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「单据」 | 路由跳转单据列表 | all |')
content = '\n'.join(lines)
with open(r'C:\Users\YKing\.openclaw\workspace\new_ch14.txt', 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Ch14: {len(content)} chars')
