# Build chapter 16 实施工具
lines = []
lines.append('---')
lines.append('')
lines.append('## 十六、实施工具')
lines.append('')
lines.append('> **功能路径**：`/tools` 模块')
lines.append('> **权限要求**：所有用户')
lines.append('> **套餐要求**：所有套餐')
lines.append('')
lines.append('### 16.1 收藏菜单')
lines.append('')
lines.append('#### 16.1.1 功能描述')
lines.append('用户收藏常用菜单，便于快速访问。')
lines.append('')
lines.append('#### 16.1.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| favorite_id | UUID | 主键 |')
lines.append('| user_id | UUID | 用户ID |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| menu_id | UUID | 收藏的菜单ID |')
lines.append('| sort_order | INT | 排序 |')
lines.append('| created_at | TIMESTAMPTZ | 收藏时间 |')
lines.append('')
lines.append('#### 16.1.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/favorites` | 收藏列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/favorites` | 添加收藏 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/favorites/{id}` | 取消收藏 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/favorites/reorder` | 排序收藏 |')
lines.append('')
lines.append('#### 16.1.4 按钮定义')
lines.append('**页面路径**: `/tools/favorites`')
lines.append('**布局**: 收藏面板（下拉或侧边栏）')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 菜单项 | 「取消收藏」 | 移除收藏 | all |')
lines.append('| 菜单项 | 「上移」 | 上移排序 | all |')
lines.append('| 菜单项 | 「下移」 | 下移排序 | all |')
lines.append('')
lines.append('### 16.2 系统广播（实施工具）')
lines.append('')
lines.append('#### 16.2.1 功能描述')
lines.append('公告管理，用于向全员推送系统公告和通知。')
lines.append('')
lines.append('#### 16.2.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| notice_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| title | VARCHAR(100) | 公告标题 |')
lines.append('| content | TEXT | 公告内容 |')
lines.append('| priority | ENUM | normal / urgent |')
lines.append('| publish_time | TIMESTAMPTZ | 发布时间 |')
lines.append('| status | ENUM | published / cancelled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 16.2.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/notices` | 公告列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/notices` | 发布公告 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/notices/{id}` | 更新公告 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/notices/{id}` | 删除公告 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/notices/{id}/cancel` | 撤回公告 |')
lines.append('')
lines.append('#### 16.2.4 按钮定义')
lines.append('**页面路径**: `/tools/notices`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「发布公告」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「撤回」 | 确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 16.3 首页配置')
lines.append('')
lines.append('#### 16.3.1 功能描述')
lines.append('用户自定义首页布局，配置显示哪些模块和组件的排列顺序。')
lines.append('')
lines.append('#### 16.3.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| home_config_id | UUID | 主键 |')
lines.append('| user_id | UUID | 用户ID |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| layout | JSONB | 首页布局配置 |')
lines.append('| widgets | JSONB | 组件列表 |')
lines.append('| updated_at | TIMESTAMPTZ | 更新时间 |')
lines.append('')
lines.append('#### 16.3.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/home/config` | 获取首页配置 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/home/config` | 保存首页配置 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/home/config/reset` | 重置为默认 |')
lines.append('')
lines.append('#### 16.3.4 按钮定义')
lines.append('**页面路径**: `/tools/home-config`')
lines.append('**布局**: 拖拽配置页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（右） | 「保存」 | 保存布局 | all |')
lines.append('| 操作栏（右） | 「重置」 | 重置为默认 | all |')
lines.append('')
lines.append('### 16.4 邮件配置')
lines.append('')
lines.append('#### 16.4.1 功能描述')
lines.append('SMTP 邮件服务器配置，支持测试连接和发送测试邮件。')
lines.append('')
lines.append('#### 16.4.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| email_config_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| smtp_host | VARCHAR(100) | SMTP 服务器地址 |')
lines.append('| smtp_port | INT | SMTP 端口 |')
lines.append('| smtp_username | VARCHAR(100) | 用户名 |')
lines.append('| smtp_password | VARCHAR(200) | 密码（加密存储） |')
lines.append('| from_email | VARCHAR(100) | 发件人邮箱 |')
lines.append('| from_name | VARCHAR(50) | 发件人名称 |')
lines.append('| use_tls | BOOLEAN | 是否使用 TLS |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('| updated_at | TIMESTAMPTZ | 更新时间 |')
lines.append('')
lines.append('#### 16.4.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/email/config` | 获取邮件配置 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/email/config` | 更新邮件配置 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/email/config/test` | 发送测试邮件 |')
lines.append('')
lines.append('#### 16.4.4 按钮定义')
lines.append('**页面路径**: `/tools/email-config`')
lines.append('**布局**: 表单页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（右） | 「保存」 | 保存表单 | tenant_admin |')
lines.append('| 操作栏（右） | 「测试」 | 发送测试邮件 | tenant_admin |')
lines.append('')
lines.append('### 16.5 消息通知')
lines.append('')
lines.append('#### 16.5.1 功能描述')
lines.append('站内消息通知，支持查看消息、标记已读、删除和批量操作。')
lines.append('')
lines.append('#### 16.5.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| message_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| user_id | UUID | 接收用户 |')
lines.append('| title | VARCHAR(100) | 消息标题 |')
lines.append('| content | TEXT | 消息内容 |')
lines.append('| message_type | ENUM | system / workflow / alert / custom |')
lines.append('| is_read | BOOLEAN | 是否已读 |')
lines.append('| read_at | TIMESTAMPTZ | 阅读时间 |')
lines.append('| created_at | TIMESTAMPTZ | 发送时间 |')
lines.append('')
lines.append('#### 16.5.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/messages` | 消息列表 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/messages/{id}` | 消息详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/messages/{id}/read` | 标记已读 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/messages/read-all` | 全部已读 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/messages/{id}` | 删除消息 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/messages/read` | 删除已读消息 |')
lines.append('')
lines.append('#### 16.5.4 按钮定义')
lines.append('**页面路径**: `/tools/messages`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（左） | 「类型筛选」 | 下拉筛选 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「全部已读」 | 确认弹窗 | all |')
lines.append('| 操作栏（右） | 「删除已读」 | 确认弹窗 | all |')
lines.append('| 表格行 | 「详情」 | 打开抽屉 | all |')
lines.append('| 表格行 | 「标记已读」 | 更新状态 | all |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | all |')
lines.append('')
lines.append('### 16.6 系统版本信息')
lines.append('')
lines.append('#### 16.6.1 功能描述')
lines.append('展示系统当前版本信息、健康检查状态和能力清单。')
lines.append('')
lines.append('#### 16.6.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| version_id | UUID | 主键 |')
lines.append('| version | VARCHAR(20) | 系统版本号 |')
lines.append('| build_number | VARCHAR(30) | 构建号 |')
lines.append('| release_date | DATE | 发布日期 |')
lines.append('| environment | ENUM | development / testing / production |')
lines.append('| capabilities | JSONB | 系统能力清单 |')
lines.append('')
lines.append('#### 16.6.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/system/version` | 获取版本信息 |')
lines.append('| GET | `/api/v1/system/health` | 健康检查 |')
lines.append('| GET | `/api/v1/system/capabilities` | 获取系统能力清单 |')
lines.append('')
lines.append('#### 16.6.4 按钮定义')
lines.append('**页面路径**: `/tools/about`')
lines.append('**布局**: 信息展示页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏 | 「检查更新」 | 检查新版本 | all |')
lines.append('| 操作栏 | 「健康检查」 | 触发健康检查 | all |')
lines.append('')
lines.append('### 16.7 外部服务')
lines.append('')
lines.append('#### 16.7.1 功能描述')
lines.append('第三方系统集成配置，支持配置外部 API 连接信息并测试连通性。')
lines.append('')
lines.append('#### 16.7.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| service_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| service_name | VARCHAR(50) | 服务名称 |')
lines.append('| service_type | ENUM | wechat / dingtalk / feishu / custom |')
lines.append('| api_endpoint | VARCHAR(500) | API 地址 |')
lines.append('| app_key | VARCHAR(100) | App Key |')
lines.append('| app_secret | VARCHAR(200) | App Secret（加密） |')
lines.append('| extra_config | JSONB | 额外配置 |')
lines.append('| status | ENUM | active / disabled / error |')
lines.append('| last_sync_at | TIMESTAMPTZ | 最后同步时间 |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 16.7.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/external-services` | 服务列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/external-services` | 新建服务 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/external-services/{id}` | 服务详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/external-services/{id}` | 更新服务 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/external-services/{id}` | 删除服务 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/external-services/{id}/test` | 测试连通性 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/external-services/{id}/sync` | 同步数据 |')
lines.append('')
lines.append('#### 16.7.4 按钮定义')
lines.append('**页面路径**: `/tools/external-services`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建服务」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「测试」 | 确认弹窗后测试 | tenant_admin |')
lines.append('| 表格行 | 「同步」 | 触发数据同步 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 16.8 系统参数设置')
lines.append('')
lines.append('#### 16.8.1 功能描述')
lines.append('Key-Value 键值对配置存储，用于存储系统运行参数和业务开关。')
lines.append('')
lines.append('#### 16.8.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| param_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户（NULL为平台级） |')
lines.append('| param_key | VARCHAR(100) | 参数键 |')
lines.append('| param_value | TEXT | 参数值 |')
lines.append('| value_type | ENUM | string / number / boolean / json |')
lines.append('| description | VARCHAR(200) | 参数描述 |')
lines.append('| is_system | BOOLEAN | 是否系统内置（不可删除） |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('| updated_at | TIMESTAMPTZ | 更新时间 |')
lines.append('')
lines.append('#### 16.8.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/params` | 参数列表 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/params/{key}` | 获取单个参数 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/params` | 创建参数 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/params/{key}` | 更新参数 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/params/{key}` | 删除参数 |')
lines.append('')
lines.append('#### 16.8.4 按钮定义')
lines.append('**页面路径**: `/tools/params`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建参数」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
content = '\n'.join(lines)
with open(r'C:\Users\YKing\.openclaw\workspace\new_ch16.txt', 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Ch16: {len(content)} chars')
