# Build chapter 13 content
lines = []
lines.append('## 十三、基础管理（档案/调度/菜单/日志/字典等）')
lines.append('')
lines.append('> **功能路径**：`/system` 模块')
lines.append('> **权限要求**：租户管理员（tenant_admin）')
lines.append('> **套餐要求**：基础版及以上')
lines.append('')
lines.append('### 13.1 基础档案')
lines.append('')
lines.append('#### 13.1.1 功能描述')
lines.append('基础档案用于管理企业的通用业务档案数据，支持树形层级结构和标准 CRUD 操作。档案类型由管理员自定义，每种档案可维护独立的字段结构。')
lines.append('')
lines.append('#### 13.1.2 数据表')
lines.append('档案分类表（archive_category）：')
lines.append('')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| category_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| category_name | VARCHAR(50) | 分类名称 |')
lines.append('| category_code | VARCHAR(30) | 分类编码（唯一） |')
lines.append('| parent_id | UUID | 上级分类（NULL表示根） |')
lines.append('| icon | VARCHAR(50) | 图标 |')
lines.append('| sort_order | INT | 排序 |')
lines.append('| field_schema | JSONB | 字段定义 JSON Schema |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('档案数据表（archive_record）：')
lines.append('')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| record_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| category_id | UUID | 档案分类 |')
lines.append('| parent_id | UUID | 上级档案（树形） |')
lines.append('| record_code | VARCHAR(50) | 档案编码 |')
lines.append('| record_name | VARCHAR(100) | 档案名称 |')
lines.append('| data | JSONB | 档案数据（动态字段） |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('| updated_at | TIMESTAMPTZ | 更新时间 |')
lines.append('')
lines.append('#### 13.1.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/archives/categories` | 获取档案分类树 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/archives/categories` | 新建档案分类 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/archives/categories/{id}` | 更新档案分类 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/archives/categories/{id}` | 删除档案分类 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/archives/records` | 档案数据列表（分页+树形） |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/archives/records` | 新建档案数据 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/archives/records/{id}` | 档案数据详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/archives/records/{id}` | 更新档案数据 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/archives/records/{id}` | 删除档案数据 |')
lines.append('')
lines.append('#### 13.1.4 按钮定义')
lines.append('**页面路径**: `/system/archives`')
lines.append('**布局**: 左侧树 + 右侧列表')
lines.append('')
lines.append('**按钮定义**:')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建档案」 | 打开全屏模态 | tenant_admin |')
lines.append('| 操作栏（右） | 「新建分类」 | 打开抽屉 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 13.2 调度计划')
lines.append('')
lines.append('#### 13.2.1 功能描述')
lines.append('调度计划管理 Cron 定时任务，支持可视化配置执行周期、任务脚本和告警规则。')
lines.append('')
lines.append('#### 13.2.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| job_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| job_name | VARCHAR(100) | 任务名称 |')
lines.append('| job_code | VARCHAR(50) | 任务编码（唯一） |')
lines.append('| job_type | ENUM | http / script / mq |')
lines.append('| cron_expression | VARCHAR(50) | Cron 表达式 |')
lines.append('| endpoint | VARCHAR(500) | HTTP 接口地址（HTTP类型） |')
lines.append('| script_content | TEXT | 脚本内容（Script类型） |')
lines.append('| params | JSONB | 任务参数 |')
lines.append('| timeout_seconds | INT | 超时时间（秒） |')
lines.append('| retry_count | INT | 重试次数 |')
lines.append('| status | ENUM | active / paused / stopped |')
lines.append('| last_run_at | TIMESTAMPTZ | 上次执行时间 |')
lines.append('| last_run_status | ENUM | success / failed / running |')
lines.append('| next_run_at | TIMESTAMPTZ | 下次执行时间 |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 13.2.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/jobs` | 任务列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/jobs` | 创建任务 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/jobs/{id}` | 任务详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/jobs/{id}` | 更新任务 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/jobs/{id}` | 删除任务 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/jobs/{id}/execute` | 手动执行一次 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/jobs/{id}/pause` | 暂停任务 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/jobs/{id}/resume` | 恢复任务 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/jobs/{id}/logs` | 执行日志 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/jobs/cron/validate` | 验证 Cron 表达式 |')
lines.append('')
lines.append('#### 13.2.4 按钮定义')
lines.append('**页面路径**: `/system/scheduler`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建任务」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「立即执行」 | 确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「暂停」 | 确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「日志」 | 路由跳转日志页 | all |')
lines.append('')
lines.append('### 13.3 菜单设置')
lines.append('')
lines.append('#### 13.3.1 功能描述')
lines.append('前端动态菜单管理，支持租户自定义菜单结构、图标、路由和权限标识。')
lines.append('')
lines.append('#### 13.3.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| menu_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户（NULL表示平台级） |')
lines.append('| parent_id | UUID | 上级菜单（NULL表示根） |')
lines.append('| menu_name | VARCHAR(50) | 菜单名称 |')
lines.append('| menu_code | VARCHAR(50) | 菜单编码 |')
lines.append('| path | VARCHAR(200) | 路由路径 |')
lines.append('| component | VARCHAR(200) | 组件路径 |')
lines.append('| icon | VARCHAR(50) | 图标 |')
lines.append('| sort_order | INT | 排序 |')
lines.append('| visible | BOOLEAN | 是否显示 |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| permission | VARCHAR(50) | 权限标识 |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 13.3.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/menus` | 获取菜单树 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/menus` | 新建菜单 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/menus/{id}` | 菜单详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/menus/{id}` | 更新菜单 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/menus/{id}` | 删除菜单 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/menus/reorder` | 批量排序 |')
lines.append('')
lines.append('#### 13.3.4 按钮定义')
lines.append('**页面路径**: `/system/menus`')
lines.append('**布局**: 左侧树 + 右侧表单')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「刷新」 | 刷新树 | all |')
lines.append('| 操作栏（右） | 「新增菜单」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「新增子菜单」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 13.4 业务日志')
lines.append('')
lines.append('#### 13.4.1 功能描述')
lines.append('业务操作日志记录和查询，支持按时间、模块、操作人等维度筛选和导出。')
lines.append('')
lines.append('#### 13.4.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| log_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| user_id | UUID | 操作用户 |')
lines.append('| user_name | VARCHAR(50) | 操作用户名（冗余） |')
lines.append('| module | VARCHAR(50) | 操作模块 |')
lines.append('| action | VARCHAR(50) | 操作动作（create/update/delete） |')
lines.append('| resource_type | VARCHAR(50) | 资源类型 |')
lines.append('| resource_id | UUID | 资源ID |')
lines.append('| detail | JSONB | 操作详情（旧值/新值） |')
lines.append('| ip_address | VARCHAR(50) | IP 地址 |')
lines.append('| user_agent | VARCHAR(200) | 浏览器标识 |')
lines.append('| created_at | TIMESTAMPTZ | 操作时间 |')
lines.append('')
lines.append('#### 13.4.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/logs` | 日志列表（分页+筛选） |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/logs/{id}` | 日志详情 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/logs/statistics` | 日志统计 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/logs/export` | 导出日志（异步） |')
lines.append('')
lines.append('#### 13.4.4 按钮定义')
lines.append('**页面路径**: `/system/audit-logs`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（左） | 「时间范围」 | 日期范围选择器 | all |')
lines.append('| 操作栏（右） | 「导出」 | 导出Excel | tenant_admin |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 表格行 | 「详情」 | 打开抽屉 | all |')
content = '\n'.join(lines)
with open(r'C:\Users\YKing\.openclaw\workspace\new_ch13_a.txt', 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Ch13 part A: {len(content)} chars')
