# Build chapter 13 sections 13.5-13.11
lines = []
lines.append('### 13.5 系统广播')
lines.append('')
lines.append('#### 13.5.1 功能描述')
lines.append('向租户内所有用户发送全员通知，支持定时发送和撤回。')
lines.append('')
lines.append('#### 13.5.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| broadcast_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| title | VARCHAR(100) | 广播标题 |')
lines.append('| content | TEXT | 广播内容 |')
lines.append('| broadcast_type | ENUM | all / dept / role |')
lines.append('| target_scope | JSONB | 发送范围配置 |')
lines.append('| send_time | TIMESTAMPTZ | 发送时间（NULL为立即） |')
lines.append('| published_at | TIMESTAMPTZ | 发布时间 |')
lines.append('| status | ENUM | draft / published / cancelled |')
lines.append('| created_by | UUID | 创建人 |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 13.5.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/broadcasts` | 广播列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/broadcasts` | 创建广播 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/broadcasts/{id}` | 广播详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/broadcasts/{id}` | 更新广播 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/broadcasts/{id}` | 删除广播 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/broadcasts/{id}/publish` | 发布广播 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/broadcasts/{id}/cancel` | 撤回广播 |')
lines.append('')
lines.append('#### 13.5.4 按钮定义')
lines.append('**页面路径**: `/system/broadcasts`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建广播」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「发布」 | 确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「撤回」 | 确认弹窗 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 13.6 校验规则配置')
lines.append('')
lines.append('#### 13.6.1 功能描述')
lines.append('管理表单字段的校验规则，支持正则表达式和自定义错误消息。')
lines.append('')
lines.append('#### 13.6.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| rule_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| rule_name | VARCHAR(50) | 规则名称 |')
lines.append('| rule_code | VARCHAR(30) | 规则编码 |')
lines.append('| field_type | ENUM | string / number / date / phone / email / idcard |')
lines.append('| pattern | VARCHAR(200) | 正则表达式 |')
lines.append('| min_length | INT | 最小长度 |')
lines.append('| max_length | INT | 最大长度 |')
lines.append('| error_message | VARCHAR(200) | 错误提示消息 |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 13.6.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/validation-rules` | 规则列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/validation-rules` | 新建规则 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/validation-rules/{id}` | 规则详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/validation-rules/{id}` | 更新规则 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/validation-rules/{id}` | 删除规则 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/validation-rules/{id}/test` | 测试规则 |')
lines.append('')
lines.append('#### 13.6.4 按钮定义')
lines.append('**页面路径**: `/system/validation-rules`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建规则」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「测试」 | 打开抽屉 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 13.7 支付配置')
lines.append('')
lines.append('#### 13.7.1 功能描述')
lines.append('配置支付渠道，包括微信支付、支付宝等第三方支付通道。')
lines.append('')
lines.append('#### 13.7.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| channel_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| channel_name | VARCHAR(50) | 渠道名称 |')
lines.append('| channel_type | ENUM | wechat / alipay / unionpay |')
lines.append('| app_id | VARCHAR(100) | 应用ID |')
lines.append('| merchant_id | VARCHAR(50) | 商户号 |')
lines.append('| api_key | VARCHAR(200) | API密钥（加密存储） |')
lines.append('| cert_path | VARCHAR(500) | 证书路径 |')
lines.append('| status | ENUM | active / disabled / testing |')
lines.append('| is_default | BOOLEAN | 是否默认渠道 |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('| updated_at | TIMESTAMPTZ | 更新时间 |')
lines.append('')
lines.append('#### 13.7.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/payment-channels` | 支付渠道列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/payment-channels` | 新建支付渠道 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/payment-channels/{id}` | 渠道详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/payment-channels/{id}` | 更新渠道配置 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/payment-channels/{id}` | 删除渠道 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/payment-channels/{id}/test` | 测试支付通道 |')
lines.append('')
lines.append('#### 13.7.4 按钮定义')
lines.append('**页面路径**: `/system/payment-channels`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建渠道」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「测试」 | 确认弹窗后测试 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 13.8 测试表单')
lines.append('')
lines.append('#### 13.8.1 功能描述')
lines.append('为开发测试阶段提供临时表单数据录入，支持提交后查看数据。')
lines.append('')
lines.append('#### 13.8.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| form_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| form_name | VARCHAR(50) | 表单名称 |')
lines.append('| form_schema | JSONB | 表单 Schema |')
lines.append('| submissions | JSONB[] | 提交记录数组 |')
lines.append('| total_count | INT | 提交次数 |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 13.8.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/test-forms` | 表单列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/test-forms` | 创建测试表单 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/test-forms/{id}` | 表单详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/test-forms/{id}` | 更新表单 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/test-forms/{id}` | 删除表单 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/test-forms/{id}/submit` | 提交表单数据 |')
lines.append('')
lines.append('#### 13.8.4 按钮定义')
lines.append('**页面路径**: `/system/test-forms`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建表单」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「填写」 | 打开全屏模态 | all |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 13.9 模板管理')
lines.append('')
lines.append('#### 13.9.1 功能描述')
lines.append('文档模板管理，支持上传、预览和下载各类文档模板（Word/Excel/PDF）。')
lines.append('')
lines.append('#### 13.9.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| template_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| template_name | VARCHAR(100) | 模板名称 |')
lines.append('| template_code | VARCHAR(50) | 模板编码 |')
lines.append('| template_type | ENUM | word / excel / pdf |')
lines.append('| file_url | VARCHAR(500) | 文件存储地址 |')
lines.append('| file_size | INT | 文件大小（字节） |')
lines.append('| variables | JSONB | 模板变量定义 |')
lines.append('| description | VARCHAR(200) | 模板描述 |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 13.9.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/templates` | 模板列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/templates` | 上传模板 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/templates/{id}` | 模板详情 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/templates/{id}` | 更新模板信息 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/templates/{id}` | 删除模板 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/templates/{id}/preview` | 预览模板 |')
lines.append('')
lines.append('#### 13.9.4 按钮定义')
lines.append('**页面路径**: `/system/templates`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（左） | 「类型筛选」 | 下拉筛选 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「上传模板」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「预览」 | 打开新窗口 | all |')
lines.append('| 表格行 | 「下载」 | 触发下载 | all |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
lines.append('')
lines.append('### 13.10 效率套件')
lines.append('')
lines.append('#### 13.10.1 功能描述')
lines.append('内置效率工具集，包括二维码生成、条形码生成、随机抽签、批量编号生成等常用工具。')
lines.append('')
lines.append('#### 13.10.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| tool_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户 |')
lines.append('| tool_name | VARCHAR(50) | 工具名称 |')
lines.append('| tool_code | VARCHAR(30) | 工具编码 |')
lines.append('| tool_type | ENUM | qrcode / barcode / random / batchno |')
lines.append('| config | JSONB | 工具配置参数 |')
lines.append('| usage_count | INT | 使用次数 |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 13.10.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/efficiency-tools` | 工具列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/efficiency-tools/{code}/generate` | 生成结果 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/efficiency-tools/{code}/history` | 使用历史 |')
lines.append('')
lines.append('#### 13.10.4 按钮定义')
lines.append('**页面路径**: `/system/efficiency-tools`')
lines.append('**布局**: 工具卡片网格')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 工具卡片 | 「使用」 | 打开对话框 | all |')
lines.append('| 工具卡片 | 「使用历史」 | 打开抽屉 | all |')
lines.append('')
lines.append('### 13.11 数据字典')
lines.append('')
lines.append('#### 13.11.1 功能描述')
lines.append('通用数据字典，支持租户自定义业务编码体系和维护常用选项列表。')
lines.append('')
lines.append('#### 13.11.2 数据表')
lines.append('| 字段 | 类型 | 说明 |')
lines.append('|------|------|------|')
lines.append('| dict_id | UUID | 主键 |')
lines.append('| tenant_id | UUID | 所属租户（NULL为平台级） |')
lines.append('| dict_name | VARCHAR(50) | 字典名称 |')
lines.append('| dict_code | VARCHAR(30) | 字典编码 |')
lines.append('| description | VARCHAR(200) | 说明 |')
lines.append('| items | JSONB | 字典项列表 |')
lines.append('| status | ENUM | active / disabled |')
lines.append('| created_at | TIMESTAMPTZ | 创建时间 |')
lines.append('')
lines.append('#### 13.11.3 API接口')
lines.append('| 方法 | 路径 | 说明 |')
lines.append('|------|------|------|')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/dicts` | 字典列表 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/dicts` | 新建字典 |')
lines.append('| GET | `/api/v1/tenants/{tenant_id}/dicts/{id}` | 字典详情（含字典项） |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/dicts/{id}` | 更新字典 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/dicts/{id}` | 删除字典 |')
lines.append('| POST | `/api/v1/tenants/{tenant_id}/dicts/{id}/items` | 新增字典项 |')
lines.append('| PUT | `/api/v1/tenants/{tenant_id}/dicts/{id}/items/{item_id}` | 更新字典项 |')
lines.append('| DELETE | `/api/v1/tenants/{tenant_id}/dicts/{id}/items/{item_id}` | 删除字典项 |')
lines.append('')
lines.append('#### 13.11.4 按钮定义')
lines.append('**页面路径**: `/system/data-dicts`')
lines.append('**布局**: 列表页')
lines.append('')
lines.append('| 位置 | 按钮名称 | 动作 | 权限 |')
lines.append('|------|----------|------|------|')
lines.append('| 操作栏（左） | 「搜索」 | 展开筛选面板 | all |')
lines.append('| 操作栏（右） | 「刷新」 | 刷新列表 | all |')
lines.append('| 操作栏（右） | 「新建字典」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「编辑」 | 打开全屏模态 | tenant_admin |')
lines.append('| 表格行 | 「字典项」 | 打开抽屉 | tenant_admin |')
lines.append('| 表格行 | 「删除」 | 删除确认弹窗 | tenant_admin |')
content = '\n'.join(lines)
with open(r'C:\Users\YKing\.openclaw\workspace\new_ch13_b.txt', 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Ch13 part B: {len(content)} chars')
